package yeobaek.backend.shared.exception;

/**
 * 클라이언트가 오류 응답을 기계적으로 분기하기 위한 코드.
 * HTTP 상태와는 독립이며, message는 예외 발생 지점에서 요청 문맥에 맞게 작성한다.
 */
public enum ErrorCode {

    INVALID_REQUEST,
    SPACE_NOT_FOUND,
    CONTENT_NOT_FOUND,
    CONTENT_UNAVAILABLE,
    CONTENT_LOCATION_NOT_FOUND,
    APPRECIATION_NOT_FOUND,
    SPACE_ACCESS_DENIED,
    CONTENT_NOT_BOUND,
    UNSUPPORTED_KIND,
    MEMBER_NOT_FOUND,
    BOOK_NOT_FOUND,
    BOOK_NOT_AVAILABLE,
    CLUB_NOT_FOUND,
    PUBLIC_ROOM_NOT_FOUND,
    JOIN_CODE_NOT_FOUND,
    PASSAGE_NOT_FOUND,
    SENTENCE_NOT_FOUND,
    SENTENCE_NOT_IN_CLUB_BOOK,
    COMMENT_NOT_FOUND,
    CANNOT_REPORT_OWN_COMMENT,
    CANNOT_BLOCK_SELF,
    AUTHOR_NOT_FOUND,
    DUPLICATE_AUTHOR,
    AUTHOR_NAME_MISMATCH,
    DUPLICATE_BOOK,
    NOT_CLUB_MEMBER,
    NOT_COMMENT_OWNER,
    UNAUTHORIZED,
    INTERNAL_ERROR
}
