package com.yeobaek.core.network.crash

enum class CrashOperation(
    val value: String,
) {
    SCREEN_VIEWED("screen_viewed"),
    NICKNAME_SUBMIT_STARTED("nickname_submit_started"),
    NICKNAME_SUBMIT_SUCCEEDED("nickname_submit_succeeded"),
    NICKNAME_SUBMIT_FAILED("nickname_submit_failed"),
    ONBOARDING_JOIN_STARTED("onboarding_join_started"),
    ONBOARDING_JOIN_SUCCEEDED("onboarding_join_succeeded"),
    ONBOARDING_JOIN_FAILED("onboarding_join_failed"),
    HOME_LAST_READING_LOADED("home_last_reading_loaded"),
    HOME_LAST_READING_FAILED("home_last_reading_failed"),
    HOME_GROUPS_LOADED("home_groups_loaded"),
    HOME_GROUPS_FAILED("home_groups_failed"),
    GROUP_DETAIL_LOADED("group_detail_loaded"),
    GROUP_DETAIL_FAILED("group_detail_failed"),
    GROUP_JOIN_STARTED("group_join_started"),
    GROUP_JOIN_SUCCEEDED("group_join_succeeded"),
    GROUP_JOIN_FAILED("group_join_failed"),
    GROUP_BOOKS_LOADED("group_books_loaded"),
    GROUP_BOOKS_FAILED("group_books_failed"),
    GROUP_CREATE_STARTED("group_create_started"),
    GROUP_CREATE_SUCCEEDED("group_create_succeeded"),
    GROUP_CREATE_FAILED("group_create_failed"),
    GROUP_EXIT_SUCCEEDED("group_exit_succeeded"),
    GROUP_EXIT_FAILED("group_exit_failed"),
    READER_LOAD_STARTED("reader_load_started"),
    READER_LOADED("reader_loaded"),
    READER_LOAD_FAILED("reader_load_failed"),
    READER_PREVIOUS_PAGE_LOAD("reader_previous_page_load"),
    READER_PREVIOUS_PAGE_FAILED("reader_previous_page_failed"),
    READER_NEXT_PAGE_LOAD("reader_next_page_load"),
    READER_NEXT_PAGE_FAILED("reader_next_page_failed"),
    READER_POSITION_UPDATED("reader_position_updated"),
    READER_PROGRESS_SAVE_SKIPPED("reader_progress_save_skipped"),
    READER_PROGRESS_SAVE_SUCCEEDED("reader_progress_save_succeeded"),
    READER_PROGRESS_SAVE_FAILED("reader_progress_save_failed"),
    READER_CHAPTER_SELECTED("reader_chapter_selected"),
    READER_SEEK_TARGET_MISSING("reader_seek_target_missing"),
    READER_SEEK_FAILED("reader_seek_failed"),
    COMMENT_SHEET_OPENED("comment_sheet_opened"),
    COMMENTS_LOADED("comments_loaded"),
    COMMENTS_LOAD_FAILED("comments_load_failed"),
    COMMENT_EDIT_STARTED("comment_edit_started"),
    COMMENT_SAVE_STARTED("comment_save_started"),
    COMMENT_SAVE_SUCCEEDED("comment_save_succeeded"),
    COMMENT_SAVE_FAILED("comment_save_failed"),
    COMMENT_DELETE_STARTED("comment_delete_started"),
    COMMENT_DELETE_SUCCEEDED("comment_delete_succeeded"),
    COMMENT_DELETE_FAILED("comment_delete_failed"),
}
